### ISSUE TITLE
bug: strapi port must match in the container and on local bind port

### ISSUE THREAD

**Issue by mochiruntime** [clicepfl/website#19]
There seems to be a bug when strapi is started on a given port in the container, and then port mapped to another on the local host. When loading the admin panel, the following error message is shown:

```
Strapi: Warning an error occurred while requesting the API
```

Not sure if this is caused by the port map, or because the `build` command was not executed after port changes. For now, we'll standardize such that Strapi is at port 8001 both inside and outside of the container, and we'll revisit this when we will configure the reverse proxy

**Comment by Lumycea** [comment]
According to this [post](https://stackoverflow.com/questions/70957481/strapi-warning-an-error-occurred-while-requesting-the-api), strapi needs to be built even in dev mode

**Comment by mochiruntime** [comment]
Re-closed by #21

**Comment by Robb-Fr** [comment]
I can confirm it works for me now :)
