### ISSUE TITLE
Consider Directus if SSO is required

### ISSUE THREAD

**Issue by mochiruntime** [clicepfl/website#43]
It seems [Directus](https://directus.io/) (another headless CMS) supports [SSO](https://docs.directus.io/self-hosted/sso.html) even in the free version. If SSO (e.g. Tequila) becomes a requirement, it may be worth reviewing how Directus compares to Strap and estimating if a migration is worth.

**Comment by Lumycea** [comment]
That's a great finding ! I'd been looking into adding a SSO for our services, the Strapi being one major drawback. I'm also struggling with the i18n in Strapi, perhaps it would fix that too.

I'll give it a try and keep you posted !

**Comment by Lumycea** [comment]
I've tinkered a bit with, and I really like how Directus is really hands on the table. It doesn't try to create complex abstraction, but is still very easy to use - IMO.

I still need to work a bit with it before thinking about replacing Strapi, mainly how to correctly save/load the data model in/from VCS (using `npx directus snapshot`), and export it as a types declaration for the frontend ([main candidate](https://github.com/elierotenberg/directus-typescript-gen)).

If conclusive, we'll have an internal discussion about replacing Strapi with Directus.
Thanks a lot !
